#ifndef VOXEL_H
#define VOXEL_H

#define VOXEL_REGION_SIZE 16u

#define VOXEL_PX_FACE_INDEX 0
#define VOXEL_NX_FACE_INDEX 1
#define VOXEL_PY_FACE_INDEX 2
#define VOXEL_NY_FACE_INDEX 3
#define VOXEL_PZ_FACE_INDEX 4
#define VOXEL_NZ_FACE_INDEX 5

#define NUM_CUBE_VOXEL_FACES 6

#define NUM_CUBE_VOXEL_FACE_TRIANGLES 2u
#define NUM_CUBE_VOXEL_FACE_VERTICES 4u

#define VOXEL_TYPE_AIR 0u
#define VOXEL_TYPE_GRASS 1u
#define VOXEL_TYPE_STONE 2u
#define VOXEL_TYPE_DIRT 3u

#endif